Aptech All Projects/MVC With DB/MVC With DB/Models/Blog.cs
namespace MVC_With_DB.Models
{
    public class Blog
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public String Subheading { get; set;}
        public String Content { get; set;}
        public String Author { get; set; }
        public String Image { get; set; }
       
    }
}

Aptech All Projects/MVC With DB/MVC With DB/Models/ErrorViewModel.cs
namespace MVC_With_DB.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Aptech All Projects/MVC With DB/MVC With DB/Models/Tag.cs
namespace MVC_With_DB.Models
{
    public class Tag
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Aptech All Projects/MVC With DB/MVC With DB/Controllers/BlogsController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_With_DB.Data;
using MVC_With_DB.Models;
using System.Reflection.Metadata;
using static System.Net.Mime.MediaTypeNames;

namespace MVC_With_DB.Controllers
{
    public class BlogsController : Controller
    {
        private readonly ApplicationDBContext applicationDBContext;

        public BlogsController( ApplicationDBContext applicationDBContext )
        {
            this.applicationDBContext = applicationDBContext;
        }
        public IActionResult AddBlog()
        {
            return View();
        }


        [HttpPost]
        public IActionResult AddBlog(Blog blog, IFormFile imgfile)
        {
            if (imgfile != null && imgfile.Length > 0)
            {
                var ff = Path.GetFileName(imgfile.FileName);
                Random rn = new Random();
                var ii = rn.Next(1, 200);
                var fn = ii + ff;
                var fol = Path.Combine(HttpContext.Request.PathBase.Value, "wwwroot/uploads");
                if (!Directory.Exists(fol))
                {
                    Directory.CreateDirectory(fol);
                    Directory.CreateDirectory(fol);
                }
                string fp = Path.Combine(fol, fn);
                using (var a = new FileStream(fp, FileMode.Create))
                {
                    imgfile.CopyTo(a);
                }
                var dbi = Path.Combine("uploads",fn);
                blog.Image = dbi;
                applicationDBContext.Blogs.Add(blog);
                applicationDBContext.SaveChanges();
            }
            return View();
 
        }

        public IActionResult Fetch()
        {
            return View(applicationDBContext.Blogs.ToList());
        }

        public IActionResult deleteBlog(int id)
        {
            Blog blog = applicationDBContext.Blogs.Find(id);
            applicationDBContext.Blogs.Remove(blog);
            applicationDBContext.SaveChanges();
            return RedirectToAction("Fetch");
        }

        public IActionResult editBlog(int id)
        {
            return View(applicationDBContext.Blogs.Find(id));
        }

        [HttpPost]
        public IActionResult editBlog(Blog blog)
        {
            applicationDBContext.Blogs.Update(blog);
            applicationDBContext.SaveChanges();
            return RedirectToAction("Fetch");
        }


        public IActionResult detailBlog(int id)
        {
            return View(applicationDBContext.Blogs.Find(id));
        }
    }
}

Aptech All Projects/MVC With DB/MVC With DB/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_With_DB.Models;
using System.Diagnostics;

namespace MVC_With_DB.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Aptech All Projects/MVC With DB/MVC With DB/Controllers/TagsController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_With_DB.Data;
using MVC_With_DB.Models;

namespace MVC_With_DB.Controllers
{
    public class TagsController : Controller
    {
        private readonly ApplicationDBContext applicationDBContext;

        public TagsController(ApplicationDBContext applicationDBContext)
        {
            this.applicationDBContext = applicationDBContext;
        }

        public IActionResult AddTag()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddTag(Tag addTag)
        {
            var tag = new Tag
            {
                Name = addTag.Name,
            };
            applicationDBContext.Tags.Add(addTag);
            applicationDBContext.SaveChanges();
            return View();
        }

        public IActionResult Fetch()
        {
            return View(applicationDBContext.Tags.ToList());
        }

      
        public IActionResult deleteTag(int id)
        {
           Tag tag = applicationDBContext.Tags.Find(id);
            applicationDBContext.Tags.Remove(tag);
            applicationDBContext.SaveChanges();
            return RedirectToAction("Fetch"); 
        }

        public IActionResult editTag( int id )
        {
            return View(applicationDBContext.Tags.Find(id));
        }

        [HttpPost]
        public IActionResult editTag( Tag tag )
        {
            applicationDBContext.Tags.Update(tag);
            applicationDBContext.SaveChanges();
            return RedirectToAction("Fetch");
        }
    }
}

Aptech All Projects/MVC With DB/MVC With DB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">  
    <title>MVC_With_DB - My Blogs</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_With_DB.styles.css" asp-append-version="true" />
</head>
<body >
    <header>
        <nav class="navbar navbar-dark bg-dark  mb-4">
            <div class="container-fluid">
                <h5 class="text-body-emphasis h4"><a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">My Blogs</a></h5>
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">My Blogs</h5>
                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">

                        <button type="button" class="btn btn-secondary mb-2 text-decoration-none">
                            <a class=" text-light text-decoration-none" asp-area="" asp-controller="Home" asp-action="Index">

                            Home

                            </a>
                           
                        </button>
                        <br />
                        <div class="btn-group dropend mb-2  ">
                            <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                Add
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Tags" asp-action="AddTag">Add Tags</a>
                                </li>
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Blogs" asp-action="AddBlog">Add Blogs</a>
                                </li>
                            </ul>
                        </div>
                        <br />


                        <div class="btn-group dropend mb-2 ">
                            <button type="button" class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                View
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Tags" asp-action="Fetch">View Tags</a>
                                </li>

                                <li>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Blogs" asp-action="Fetch">View Blogs</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </nav>














    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - My Blogs  By "Ashhad"- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>